server:
  port: 8222

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/wassefchargui}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
#            Dynamic routing using service discovery
            - id: department-service
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/api/v1/departements/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: departmentServiceCircuitBreaker
                    fallbackUri: forward:/fallback/department-service
            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/v1/employees/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: employeeServiceCircuitBreaker
                    fallbackUri: forward:/fallback/employee-service
          #  static routing
#            - id: employee-service
#              uri: http://localhost:8082
#              predicates:
#                - Path=/employees/**
#              filters:
#                - name: CircuitBreaker
#                  args:
#                    name: userServiceCircuitBreaker
#                    fallbackUri: forward:/fallback/employee-service



resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms



springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs
    operationsSorter: method
    display-request-duration: true
    urls:
      - url: /api-docs
        name: API Gateway Service
      - name: Employee Service API
        url: /employee-service/v3/api-docs
      - name: Department Service API
        url: /department-service/v3/api-docs


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.security: TRACE
