server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wassefchargui_db
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: department-service
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always


